name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade build tools
        run: python -m pip install --upgrade pip build twine

      - name: Clean build artifacts
        run: rm -rf build dist *.egg-info

      - name: Build package (sdist + wheel)
        run: python -m build

      - name: Twine check
        run: twine check dist/*

      - name: Verify version matches tag
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF_NAME#v}"
          PYV=$(python -c 'import tomllib; print(tomllib.load(open("pyproject.toml","rb"))["project"]["version"])')
          echo "Tag: $TAG  PyProject: $PYV"
          test "$TAG" = "$PYV"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
