name: Upload Python Package

on:
  release:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4

    - name: Upgrade build tools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel build twine

    - name: Print build tool versions
      run: |
        python -m pip --version
        python -c "import setuptools; print('setuptools', setuptools.__version__)"
        python -c "import wheel; print('wheel', wheel.__version__)"

    - name: Clean build artifacts
      run: rm -rf build dist *.egg-info

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
